name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

env:
  DOCKER_FLAGS: ""
  CI: 1

jobs:
  gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: test with gcc
        run: rake docker_test_gcc
  clang:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: test with clang
        run: rake docker_test_clang
  gem_install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: test gem install
        run: rake docker_test_gem_install
